### ISSUE TITLE
Change text in orange stripe

### ISSUE THREAD

**Issue by CodefortheCarolinas** [CodefortheCarolinas/tax-benefit-website#35]
Change text in in orange stripe to read as follows:

Participating agencies text, email, mail, or call clients to let them know that they may be eligible for tax benefits. We recommend that you use and adapt [these sample messages](https://docs.google.com/document/d/1DQ7Kfeubg0GjBg_QH7HDVxSTa8Jgk7AvRviZ8rP0k_I/edit) in your campaign.

**Comment by annelisegrimm** [comment]
Slight update here, because I agree a little explanation is helpful:

Participating agencies text, email, mail, or call clients to let them know that they may be eligible for tax benefits. We recommend that you use and adapt [these sample messages](https://docs.google.com/document/d/1DQ7Kfeubg0GjBg_QH7HDVxSTa8Jgk7AvRviZ8rP0k_I/edit) in your campaign.
